#! /usr/local/bin/python3
"""Example showing how to extend mformat with a custom format.

This example demonstrates how to create a custom format class that extends
the mformat framework. The custom format is a simple "tree" format that uses
indentation and markers to show document structure. This format is easy to
understand but is clearly not a candidate for inclusion as a standard format
in the framework.
"""

# Copyright (c) 2026 Tom Björkholm
# MIT License
#

from typing import Optional, Callable
from e01_paragraph import example_main
from mformat.mformat_textbased import MultiFormatTextBased
from mformat.mformat_state import MultiFormatState, Formatting
from mformat.mformat import FormatterDescriptor
from mformat.factory import register_mf, create_mf


class MultiFormatTree(MultiFormatTextBased):
    """A custom tree format class that extends MultiFormatTextBased.

    This class demonstrates how to create a custom format by extending
    MultiFormatTextBased (which itself extends MultiFormat). The tree format
    uses indentation and simple markers to represent document structure.

    To create a custom format, you need to:
    1. Derive from MultiFormatTextBased (for text-based formats) or MultiFormat
    2. Implement all abstract methods (marked with _must_be_overridden)
    3. Implement get_arg_desciption() class method
    4. Implement file_name_extension() class method
    5. Register the class using register_mf() from mformat.factory
    """

    def __init__(self, file_name: str, url_as_text: bool = False,
                 file_exists_callback: Optional[Callable[[str], None]] = None):
        """Initialize the TreeFormat class.

        Args:
            file_name: The name of the file to write to.
            url_as_text: Format URLs as text not clickable URLs.
            file_exists_callback: A callback function to call if the file
                                  already exists. Return to allow the file to
                                  be overwritten. Raise an exception to prevent
                                  the file from being overwritten.
        """
        # Call the parent class constructor to initialize the base class
        super().__init__(file_name=file_name, url_as_text=url_as_text,
                         file_exists_callback=file_exists_callback)

    @classmethod
    def file_name_extension(cls) -> str:
        """Get the file name extension for the formatter.

        This method must be implemented by all format classes. It returns
        the file extension (including the dot) that should be used for files
        of this format. The framework will automatically append this extension
        to the file name if it's not already present.

        Returns:
            The file extension string (e.g., '.tree').
        """
        return '.tree'

    @classmethod
    def get_arg_desciption(cls) -> FormatterDescriptor:
        """Get the description of the arguments for the formatter.

        This method must be implemented by all format classes. It returns
        a FormatterDescriptor that describes:
        - name: The format name used to create instances (e.g., 'tree')
        - mandatory_args: List of mandatory argument names (empty for this
                          format)
        - optional_args: List of optional argument names (empty for this
                         format)

        Returns:
            A FormatterDescriptor named tuple.
        """
        return FormatterDescriptor(name='tree', mandatory_args=[],
                                   optional_args=[])

    def _write_file_prefix(self) -> None:
        """Write the file prefix.

        This method is called once when the document starts. For the tree
        format, we don't need any prefix, but some formats (like HTML) might
        write a DOCTYPE declaration or opening tags here.
        """
        assert self.file is not None
        # For the tree format, we don't need a prefix
        # Just write a comment to indicate the format
        self.file.write('# Tree format document\n')
        self.file.write('# Generated by mformat\n\n')

    def _write_file_suffix(self) -> None:
        """Write the file suffix.

        This method is called once when the document ends. For the tree
        format, we don't need any suffix, but some formats (like HTML) might
        write closing tags here.
        """
        assert self.file is not None
        # For the tree format, we don't need a suffix
        # Just write a final newline for cleanliness
        self.file.write('\n')

    def _start_paragraph(self) -> None:
        """Start a paragraph.

        This method is called when a new paragraph begins. In the tree format,
        paragraphs are represented with indentation. We ensure there's a
        blank line before the paragraph for readability.
        """
        assert self.file is not None
        # Ensure we have a blank line before the paragraph
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')

    def _end_paragraph(self) -> None:
        """End a paragraph.

        This method is called when a paragraph ends. In the tree format,
        we just write a newline to separate paragraphs.
        """
        assert self.file is not None
        self.file.write('\n')

    def _start_heading(self, level: int) -> None:
        """Start a heading.

        This method is called when a new heading begins. In the tree format,
        headings are represented with '>' markers and indentation based on
        the heading level.

        Args:
            level: The heading level (1-6, where 1 is the highest level).
        """
        assert self.file is not None
        # Ensure we have a blank line before the heading
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')
        # Write indentation based on level (level 1 has no indent, level 2
        # has 2 spaces, etc.)
        indent = ' ' * (2 * (level - 1))
        # Write the heading marker: '>' repeated based on level
        self.file.write(f'{indent}{">" * level} ')

    def _end_heading(self, level: int) -> None:
        """End a heading.

        This method is called when a heading ends. In the tree format,
        we just write a newline.

        Args:
            level: The heading level (not used in this implementation, but
                   required by the interface).
        """
        assert self.file is not None
        assert isinstance(level, int)
        self.file.write('\n')

    def _write_text(self, text: str, state: MultiFormatState,
                    formatting: Formatting) -> None:
        """Write text into current item (paragraph, heading, list item, etc.).

        This method is called whenever text needs to be written. The text
        has already been encoded (special characters escaped) by the framework.
        We need to handle formatting (bold, italic) and write the text to
        the file.

        Args:
            text: The text to write (already encoded).
            state: The current state (HEADING, PARAGRAPH, etc.).
            formatting: Formatting information (bold, italic).
        """
        assert self.file is not None
        # For the tree format, we represent formatting with markers:
        # **text** for bold, *text* for italic, ***text*** for both
        formatted_text = text
        if formatting.bold and formatting.italic:
            formatted_text = f'***{text}***'
        elif formatting.bold:
            formatted_text = f'**{text}**'
        elif formatting.italic:
            formatted_text = f'*{text}*'
        self.file.write(formatted_text)

    def _write_url(self, url: str, text: Optional[str],
                   state: MultiFormatState,
                   formatting: Formatting) -> None:
        """Write a URL into current item.

        This method is called when a URL needs to be written. In the tree
        format, we represent URLs as [text](url) similar to Markdown.

        Args:
            url: The URL to write.
            text: Optional text to display for the URL.
            state: The current state (not used in this implementation).
            formatting: Formatting information (bold, italic).
        """
        assert self.file is not None
        # Use the URL as text if no text is provided
        display_text = text if text else url
        # Apply formatting to the display text
        if formatting.bold and formatting.italic:
            display_text = f'***{display_text}***'
        elif formatting.bold:
            display_text = f'**{display_text}**'
        elif formatting.italic:
            display_text = f'*{display_text}*'
        # Write the URL in [text](url) format
        self.file.write(f'[{display_text}]({url})')

    def _start_bullet_list(self, level: int) -> None:
        """Start a bullet list.

        This method is called when a new bullet list begins. In the tree
        format, we don't need to do anything special here, as the list
        structure is handled by the list items themselves.

        Args:
            level: The nesting level of the list (1-based).
        """
        assert self.file is not None
        assert isinstance(level, int)
        # For the tree format, we don't need to do anything special when
        # starting a list - the structure is shown by the items themselves

    def _end_bullet_list(self, level: int) -> None:
        """End a bullet list.

        This method is called when a bullet list ends. In the tree format,
        we just ensure there's a blank line after the list.

        Args:
            level: The nesting level of the list (1-based).
        """
        assert self.file is not None
        assert isinstance(level, int)
        # Ensure we have a blank line after the list
        last_chars = self._get_last_chars_written(num_chars=1)
        if last_chars != '\n':
            self.file.write('\n')

    def _start_bullet_item(self, level: int) -> None:
        """Start a bullet list item.

        This method is called when a new bullet list item begins. In the tree
        format, we write indentation and a bullet marker based on the level.

        Args:
            level: The nesting level of the item (1-based).
        """
        assert self.file is not None
        assert isinstance(level, int)
        # Ensure we have a blank line before the item if needed
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')
        # Write indentation: 2 spaces per level (level 1 has no indent)
        indent = ' ' * (2 * (level - 1))
        # Use different bullet markers for different levels
        bullets = ['•', '◦', '▪', '▫']
        bullet = bullets[min(level - 1, len(bullets) - 1)]
        self.file.write(f'{indent}{bullet} ')

    def _end_bullet_item(self, level: int) -> None:
        """End a bullet list item.

        This method is called when a bullet list item ends. In the tree
        format, we just write a newline.

        Args:
            level: The nesting level of the item (1-based).
        """
        assert self.file is not None
        _ = level  # pylint: disable=unused-variable
        self.file.write('\n')

    def _start_numbered_list(self, level: int) -> None:
        """Start a numbered list.

        This method is called when a new numbered list begins. In the tree
        format, we don't need to do anything special here.

        Args:
            level: The nesting level of the list (1-based).
        """
        assert self.file is not None
        _ = level  # pylint: disable=unused-variable
        # For the tree format, we don't need to do anything special when
        # starting a list - the structure is shown by the items themselves

    def _end_numbered_list(self, level: int) -> None:
        """End a numbered list.

        This method is called when a numbered list ends. In the tree format,
        we just ensure there's a blank line after the list.

        Args:
            level: The nesting level of the list (1-based).
        """
        assert self.file is not None
        _ = level  # pylint: disable=unused-variable
        # Ensure we have a blank line after the list
        last_chars = self._get_last_chars_written(num_chars=1)
        if last_chars != '\n':
            self.file.write('\n')

    def _start_numbered_item(self, level: int, num: int,
                             full_number: str) -> None:
        """Start a numbered list item.

        This method is called when a new numbered list item begins. In the
        tree format, we write indentation and the number.

        Args:
            level: The nesting level of the item (1-based).
            num: The number of the item at this level.
            full_number: The full number including all levels (e.g., "1.2.3").
        """
        assert self.file is not None
        _ = level  # pylint: disable=unused-variable
        assert isinstance(num, int)
        assert isinstance(full_number, str)
        # Ensure we have a blank line before the item if needed
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')
        # Write indentation: 2 spaces per level (level 1 has no indent)
        indent = ' ' * (2 * (level - 1))
        # Write the number followed by a period and space
        self.file.write(f'{indent}{full_number}. ')

    def _end_numbered_item(self, level: int, num: int) -> None:
        """End a numbered list item.

        This method is called when a numbered list item ends. In the tree
        format, we just write a newline.

        Args:
            level: The nesting level of the item (1-based).
            num: The number of the item at this level.
        """
        assert self.file is not None
        _ = level  # pylint: disable=unused-variable
        assert isinstance(num, int)
        self.file.write('\n')

    def _start_table(self, num_columns: int) -> None:
        """Start a table.

        This method is called when a new table begins. In the tree format,
        we write a blank line before the table.

        Args:
            num_columns: The number of columns in the table.
        """
        assert self.file is not None
        _ = num_columns  # pylint: disable=unused-variable
        # Ensure we have a blank line before the table
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')

    def _end_table(self, num_columns: int, num_rows: int) -> None:
        """End a table.

        This method is called when a table ends. In the tree format,
        we write a blank line after the table.

        Args:
            num_columns: The number of columns in the table.
            num_rows: The number of rows in the table.
        """
        assert self.file is not None
        _ = num_columns  # pylint: disable=unused-variable
        _ = num_rows  # pylint: disable=unused-variable
        self.file.write('\n')

    def _write_table_first_row(self, first_row: list[str],
                               formatting: Formatting) -> None:
        """Write the first row of a table.

        This method is called to write the header row of a table. In the
        tree format, we write the row with special formatting to indicate
        it's a header.

        Args:
            first_row: The cells of the first row (already encoded).
            formatting: Formatting information for the row.
        """
        assert self.file is not None
        # For the tree format, we write the header row with a special marker
        # We'll use '|' to separate columns
        formatted_row = []
        for cell in first_row:
            # Apply formatting if needed
            formatted_cell = cell
            if formatting.bold and formatting.italic:
                formatted_cell = f'***{cell}***'
            elif formatting.bold:
                formatted_cell = f'**{cell}**'
            elif formatting.italic:
                formatted_cell = f'*{cell}*'
            formatted_row.append(formatted_cell)
        # Write the row with column separators
        self.file.write('| ' + ' | '.join(formatted_row) + ' |\n')
        # Write a separator line
        assert self.table is not None
        separator = '|-' + '-|-'.join(['-' * width
                                       for width in
                                       self.table.column_widths]) + '-|'
        self.file.write(separator + '\n')

    def _write_table_row(self, row: list[str], formatting: Formatting,
                         row_number: int) -> None:
        """Write a row of a table.

        This method is called to write a data row of a table. In the tree
        format, we write the row with column separators.

        Args:
            row: The cells of the row (already encoded).
            formatting: Formatting information for the row.
            row_number: The row number (0-based, excluding header).
        """
        assert self.file is not None
        assert self.table is not None
        # Format each cell
        formatted_row: list[str] = []
        for cell in row:
            # Apply formatting if needed
            formatted_cell = cell
            if formatting.bold and formatting.italic:
                formatted_cell = f'***{cell}***'
            elif formatting.bold:
                formatted_cell = f'**{cell}**'
            elif formatting.italic:
                formatted_cell = f'*{cell}*'
            # Pad the cell to match the column width
            col_idx = len(formatted_row)
            if col_idx < len(self.table.column_widths):
                width = self.table.column_widths[col_idx]
                formatted_cell = formatted_cell.ljust(width)
            formatted_row.append(formatted_cell)
        # Write the row with column separators
        self.file.write('| ' + ' | '.join(formatted_row) + ' |\n')

    def _start_code_block(self, programming_language: Optional[str]) -> None:
        """Start a code block.

        This method is called when a code block begins. In the tree format,
        we write a marker to indicate the start of a code block.

        Args:
            programming_language: Optional programming language name.
        """
        assert self.file is not None
        # Ensure we have a blank line before the code block
        last_chars = self._get_last_chars_written(num_chars=2)
        if last_chars != '\n\n' and last_chars[-1:] != '\n':
            self.file.write('\n')
        # Write a marker for the code block
        lang_text = (f' ({programming_language})'
                     if programming_language else '')
        self.file.write(f'```CODE{lang_text}\n')

    def _end_code_block(self, programming_language: Optional[str]) -> None:
        """End a code block.

        This method is called when a code block ends. In the tree format,
        we write a marker to indicate the end of a code block.

        Args:
            programming_language: Optional programming language name.
        """
        assert self.file is not None
        self.file.write('```\n')

    def _write_code_block(self, text: str,
                          programming_language: Optional[str]) -> None:
        """Write a code block.

        This method is called to write the content of a code block. In the
        tree format, we write the text verbatim (it's already been encoded
        by the framework).

        Args:
            text: The code block text (already encoded).
            programming_language: Optional programming language name.
        """
        assert self.file is not None
        self.file.write(text)

    def _encode_text(self, text: str) -> str:
        """Encode text (escape special characters).

        This method is called by the framework to escape special characters
        that might have special meaning in the format. For the tree format,
        we need to escape characters that could interfere with our markers.

        Note: We don't escape asterisks here because they're used for
        formatting in _write_text. The framework ensures that text passed
        to _write_text has been encoded, and we add formatting markers
        separately, so escaped asterisks in the text won't interfere.

        Args:
            text: The text to encode.

        Returns:
            The encoded text with special characters escaped.
        """
        if not text:
            return text
        # For the tree format, we need to escape characters that could
        # interfere with our markers: |, [, ], (, ), `
        # We'll use backslash escaping
        result = text
        # Escape backslashes first (must be first to avoid double-escaping)
        result = result.replace('\\', '\\\\')
        # Escape pipe characters (used in tables)
        result = result.replace('|', '\\|')
        # Escape square brackets and parentheses (used in URLs)
        # Note: We escape these even though they're used in URLs, because
        # we want literal brackets/parentheses in text to be escaped
        result = result.replace('[', '\\[')
        result = result.replace(']', '\\]')
        result = result.replace('(', '\\(')
        result = result.replace(')', '\\)')
        # Note: We don't escape asterisks here because:
        # 1. They're used for formatting in _write_text
        # 2. The formatting markers are added separately from the text
        # 3. If the user wants literal asterisks, they should appear as-is
        #    (they won't interfere with our formatting markers)
        # Escape backticks (used in code blocks)
        result = result.replace('`', '\\`')
        return result


def custom_format_example(format_name: str, file_name: str) -> None:
    """Write an example file demonstrating the custom tree format.

    This function demonstrates how to register and then use the custom
    format (or any format) to write a document. The same code works
    for all formats registered with the framework.

    Args:
        format_name: The name of the format to use (e.g., 'tree', 'html',
                     'md').
        file_name: The name of the output file.
    """
    # The factory will automatically create the correct format class based
    # on the format_name. The file extension will be added automatically
    # if not present.
    with create_mf(format_name=format_name, file_name=file_name) as mf:
        # Write a heading
        mf.new_heading(level=1, text='Custom Format Example')
        # Write a paragraph
        mf.new_paragraph('This example demonstrates how to create and use '
                         'a custom format in the mformat framework.')
        mf.add_text('The same code can be used to write to different formats, '
                    'just by changing the format name.')
        # Write another heading
        mf.new_heading(level=2, text='Features')
        # Write a bullet list
        mf.new_bullet_item('Easy to extend the framework')
        mf.new_bullet_item('Supports all standard document elements')
        mf.new_bullet_item('Format-agnostic API')
        # Write a numbered list
        mf.new_numbered_point_item('First step: Create a format class')
        mf.new_numbered_point_item('Second step: Implement required methods')
        mf.new_numbered_point_item('Third step: Register the format')
        # Write a table
        mf.write_complete_table([
            ['Element', 'Method'],
            ['Paragraph', 'new_paragraph()'],
            ['Heading', 'new_heading()'],
            ['List', 'new_bullet_item()'],
        ], bold_first_row=True)
        # Write a code block
        mf.write_code_block('def example():\n    print("Hello, World!")',
                            programming_language='python')
        # Write a paragraph with formatting
        mf.new_paragraph('This text is ', bold=False, italic=False)
        mf.add_text('bold', bold=True, italic=False)
        mf.add_text(' and this is ', bold=False, italic=False)
        mf.add_text('italic', bold=False, italic=True)
        mf.add_text('.', bold=False, italic=False)
        # Write a URL
        mf.new_paragraph('Visit ')
        mf.add_url('https://example.com', text='our website',
                   bold=False, italic=False)


# Register the custom format with the factory. This makes the format
# available through create_mf() and list_registered_mf()
# The registration must happen before using the format
# and before the example_main function is called as example_main
# function does call list_registered_mf() to list the available formats.
register_mf(MultiFormatTree)


if __name__ == "__main__":
    # Use the example_main function from e01_paragraph.py to handle
    # command-line arguments and run the example
    # This provides a consistent interface for all examples
    example_main(example_text='Custom Format', function=custom_format_example)
